id: P005594
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:05:36.575035
source_metadata:
  id: bdr:W21498
  title: པ་སྣམ་དགའ་སྡོང་མཚན་སྒྲོགས་དགའ་ལྡན་དར་རྒྱས་གླིང་དགོན་གྱི་ལོ་རྒྱུས་དད་ལྡན་དགའ་བའི་གཏམ
  author: ''
  volumes:
    7d87eaec756448928278ffc1fca8d1c4:
      image_group_id: I1PD11015
      title: ''
      volume_number: 1
      total_pages: 88
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
